// The publishable package has two outputs: plain ESM/declarations for imports,
// and a copy of the already-built static viewer, its assets, for mounting. The
// standalone site continues to use its vendored Three.js; imported models use
// the consuming application's Three.js through a small forwarding module, and the
// mounted viewer uses the host's engine when the host offers it (three-engine.ts).
import { execFileSync } from "node:child_process";
import { cp, mkdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import { buildSite, dist, root, src } from "./build-site.js";

export async function buildPackage() {
  const lib = path.join(root, "lib"), site = path.join(root, "site");
  await buildSite();
  await rm(lib, { recursive: true, force: true });
  await rm(site, { recursive: true, force: true });
  const compiler = path.join(path.dirname(createRequire(import.meta.url).resolve("typescript/package.json")), "bin/tsc");
  execFileSync(process.execPath, [compiler, "-p", path.join(src, "tsconfig.package.json")], { cwd: root, stdio: "inherit" });
  await mkdir(path.join(lib, "vendor"), { recursive: true });
  // Preserve all source geometry and import paths while sharing the host's
  // engine. This is a new package shim, not a modification of the vendor bundle.
  const forwarding = 'export * from "three";\n';
  await writeFile(path.join(lib, "vendor/three-r186.js"), forwarding);
  await writeFile(path.join(lib, "vendor/three-r186.d.ts"), forwarding);
  await cp(dist, site, { recursive: true });
  await shareHostEngine(site);
  console.log("Built package ESM and declarations in lib/, with viewer assets in site/.");
}

// In the assets, the scene's modules import Three.js from vendor/three-r186.js, as on the
// site. Here that becomes a module that takes the host's engine when the host offered one,
// and otherwise imports the vendored bundle, kept beside it as three-r186.bundle.js. It names
// the bundle's exports, which `@a2f0/skyline/three` (skyline-three.ts) also exports from the
// host's `three`; the package suite checks they match.
export async function shareHostEngine(site: string) {
  const vendor = path.join(site, "vendor");
  const names = Object.keys(await import(path.join(src, "vendor/three-r186.js"))).sort();
  await rename(path.join(vendor, "three-r186.js"), path.join(vendor, "three-r186.bundle.js"));
  await writeFile(path.join(vendor, "three-r186.js"), `// Generated by scripts/build-package.ts: the Three.js the viewer's scene renders with. The
// host's engine when the page offered one (mountSkyline's \`three\` option), and otherwise the
// vendored bundle beside this file, which then loads only when a scene first needs it.
import { providedThree } from "../three-engine.js";
const vendored = () => import("./three-r186.bundle.js");
const host = providedThree();
const engine = host ? await host.catch((error) => {
  console.warn("The Chicago skyline could not use the page's Three.js, so it loads its own:", error);
  return vendored();
}) : await vendored();
export const { ${names.join(", ")} } = engine;
`);
}

if (import.meta.main) buildPackage().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
